# Generated by Django 3.1.3 on 2021-11-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_club', '0002_auto_20211108_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_score',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
